#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 24 07:38:37 2019

@author: anna
"""

import networkx as nx
#networkx creates graphs, functions include Graph(), add_nodes, add_edges
G=nx.Graph()

class DAG(nodes, edges):

    def __init__(self):
        self.nx.Graph()
    
    def add_node(nodes):
        for i in nodes:
            nx.add_node(i)
    
    def add_edges(edges):
        for i in edges:
            nx.add_egdes
            

##Note sure yet what to put here
class node(name, number):
    
    def __init__(self):
        